### ISSUE TITLE
Using TypeScript modules

### ISSUE THREAD

**Issue by filipstachura** [meteor-typescript/meteor-typescript-compiler#16]
Hi guys,

Is it possible to use TypeScript modules within my meteor project? I tried to find an example in meteor-typescript-demos repository, but unsuccessfully.

In best case scenario I would like to create separate *.ts files with self defined modules and namespaces. Please let me know if you need any other information.

Thanks for great work!

**Comment by musically-ut** [comment]
**Short answer:** If you mean using Typescript modules as AMD/CommonJS/RequireJS modules, I don't think it is possible.

**Long answer:** The way this plugin works is by individually compiling each `ts` file **individually** to a `js` file and adding it to the list of javascript source code which Meteor sees. Meteor then bundles all of it up and serves it as a single JS file to the client. The order in which these are bundled together cannot be controlled yet. Hence, you cannot ensure (as `tsc` can) that the modules are compiled in correctly. The most you can do is reference individual files using `/// <reference path="..." />` syntax for type checking.

The Meteor build system would need to change before such module imports can be allowed.

In order to use the module system myself (and to use the latest typescript compiler), I ended up with a somewhat clumsy setup: [musically-ut/meteor-typescript-seed](https://github.com/musically-ut/meteor-typescript-seed).
That setup is working nicely for me and I will stick to it until Meteor makes its build system more flexible **and** Typescript releases a stable API interface (the API has changed significantly from 1.0 to 1.3 and the `npm-package` this package depends on have not yet been updated).

**Comment by orefalo** [comment]
TS Stable API is a good point.  typescript-compiler is based on 0.9 for that very reason. Originally, I was resistant, and surprised to see M$ publish an OSS project that great - well it comes with a legacy.

The typescript-compiler project is supposed to take care of the compilation of .ts assets transparently. No need to watch from the command line. With that said, meteor build system is VERY BASIC and doesn't have the notion of a set of files: it compiles files one after the other. This has a negative impact on TS compilation performance which would benefit from reusing the same compiler instance to compile multiple assets.

**Comment by musically-ut** [comment]
The TS compilation performance has increased quite a bit between 1.0 and 1.3. Just moving the underlying API support from 1.0 to 1.3 will already alleviate much of the compilation pain even without reusing the compiler instance across compilations. I tried doing it for a while back in December. However, IIRC speed is not the only issue, doesn't referencing `.ts` files instead of `.d.ts` files in the typescript code also cause the same code to be included multiple times in the resulting `js` bundle?

**Comment by orefalo** [comment]
Please define IIRC

What do you mean by referencing ts vs .d.ts

regarding the open APi, I was thinking about changing the code to use a command line compiler rather than the inline one. I just don't have time.

**Comment by musically-ut** [comment]
IIRC == If I Recall Correctly :)

And let's say in `bar.ts`, I need to use a module I defined in `foo.ts`. Then I can use either of the following for type-checking `bar.ts`:

    /// <reference path="foo.d.ts" />

or

    /// <reference path="foo.ts" />

However, if I remember correctly, if I point to `foo.ts`, then typescript would actually pull the code from `foo.ts` into the resulting `bar.js`. That would mean that the code corresponding to `foo.ts` would get bundled at least twice: once as `foo.js` and then again as part of `bar.js`. Hence, the recommendation _somewhere_ was to maintain a separate definition file for each typescript file. But I may be misremembering things here.

*On using the new compiler from the command line v/s using the old compiler inline*: I also think that even after taking into account the delay caused in invoking a separate process, the end result would still be faster if `meteor-typescript-compiler` moves to the new compiler.

**Comment by orefalo** [comment]
closing demo helloworld is working fine - need to add another example (todos)

**Comment by tomitrescak** [comment]
I have dealt with this issue on my [blog](https://doctorllama.wordpress.com/2015/04/21/meteor-typescript-classes-and-modules/) and [here](http://stackoverflow.com/questions/28321467/using-modules-in-meteor-js-with-typescript). I decided to use the evil `eval` command, since it gave me the easiest possibility of using modules till something more sophisticated appears.

Placing following eval before any module will allow you to use the module system in typescript.

```
eval('var ModuleName = (ModuleName || (ModuleName = {})');
```
