### ISSUE TITLE
"Could not find tsc binary, defaulting to 'tsc'" on Windows

### ISSUE THREAD

**Issue by maxfriedmann** [meteor-typescript/meteor-typescript-compiler#26]
Hi,
I get "Could not find tsc binary, defaulting to 'tsc'" on Windows even though I have typescript installed. Afterwards the tsc.js file is being opened and no ts files are compiled. 

I have typescript 1.5.0-beta installed globally. 

Should your package work on windows?

**Comment by shadyendless** [comment]
Hey everyone! I have a fix (I think). Assuming that you installed TypeScript for Visual Studio (required for this to work!), type the following in the console (after going to the directory of your project):

`meteor remove meteor add meteortypescript:compiler`

`meteor add meteor add shadyendless:typescript-compiler`

This is only a temporary fix until meteor-typescript adds it to the official repository (after which I will pull mine down).

To meteor-typescript, in order to fix this, please add the following code to your plugin/compile-tsc.js inside the concat on line 43:

`glob.sync("C:/Program Files (x86)/Microsoft SDKs/TypeScript/**/tsc.exe"),`

**Comment by orefalo** [comment]
Plz submit a pull req

**Comment by shadyendless** [comment]
I've never helped contribute to a repository. How does one go about doing that?

**Comment by orefalo** [comment]
Congrats and thank you! ;-) closing
