### ISSUE TITLE
Update .tsconfig file in sample

### ISSUE THREAD

**Issue by dbx834** [meteor-typescript/meteor-typescript-compiler#49]
Hi,

Been trying to get TypeScript to work with Meteor. Have been studying the sample project. I could not find reference for some configuration options,

- alwaysThrow
- useCache

I tried looking at these places,

- https://github.com/Microsoft/TypeScript/wiki/tsconfig.json
- https://github.com/Microsoft/TypeScript/wiki/Compiler-Options
- http://json.schemastore.org/tsconfig

I assume when you created this project these options were there? Could you please update the .tsconfig file to the most recent practices. 

Thanks!

**Comment by barbatus** [comment]
`tsconfig.json` is the name of the TypeScript file, `.tsconfig` is very outdated name.
This package has been recently updated, please try the latest version.
Options you pointed out don't work any more.  Otherwise, all valid compiler options are described here http://www.typescriptlang.org/docs/handbook/compiler-options.html.
